name: point_meteo
description: "Une application Flutter pour afficher les prévisions météorologiques basées sur la localisation de l'utilisateur."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  intl: ^0.20.2
  cupertino_icons: ^1.0.8
  geolocator: ^14.0.2
  weather_icons: ^3.0.0
  shared_preferences: ^2.5.4
  flutter_animate: ^4.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

# --- Configuration pour générer l'icône de l'application ---
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo.png"
  min_sdk_android: 21